//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I add an invoice to credit card vendor ? 
        ///
        ///Invoices can be added to credit card vendors just like any other vendor using Accounts Payable &gt; Transactions &gt; AP Batch Entry &gt; New. Or invoices can be added directly in the  Select/Deselect for Payment menu item.  
        ///
        ///To add invoices directly from the Select/Deselect for Payment menu item. These would be the steps: 
        ///
        ///1. AP &gt; Transactions &gt; Select/Deselect Invoice for Payment
        ///2. Select credit card vendor and click OK
        ///3. Click the Add button
        ///
        ///4. To a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AP_AddInvtoCCVend {
            get {
                return ResourceManager.GetString("AP_AddInvtoCCVend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this menu item to select or deselect vendor invoices to pay in Accounts Payable &gt; Transactions &gt; Checks and Registers.    
        ///
        ///After selecting invoices to pay, the remaining steps to complete the check run are first to Prepare Check Proofing and then Checks and Registers.
        ///
        ///Accounts Payable &gt; Transactions &gt; Select/Deselect Invoices for Payment
        ///
        ///Use this screen to narrow invoices to select for payment based on currency, date range, vendor, and a User 1 field or to quickly select or deselect all invoice [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AP_SelectDeselect_HELP {
            get {
                return ResourceManager.GetString("AP_SelectDeselect_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This menu item is used to enter accounts receivable batches. The four types available are: Cash, Invoice, Credit Memo, and Adjustment.
        ///
        /// 
        ///
        ///Once batches are entered, select the X to exit. The batch(es) can be updated immediately through the Post Batches screen or at a later time through Update AR Batches.  An audit trail prints upon exiting.  Batches can be modified before update through Accounts Receivable &gt; Transactions &gt; AR Batches &gt; Open.
        ///
        /// 
        ///
        ///Note: The Business Intelligence version of the Account [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AR_TRANSACTIONS_HELP {
            get {
                return ResourceManager.GetString("AR_TRANSACTIONS_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I write off bad debt?
        ///
        ///1.Go to AR &gt; Transactions &gt; AR Batches &gt; New
        ///
        ///2.Choose an Adjustment type batch
        ///
        ///3.Enter customer, invoice number, and amount to be adjusted.  
        ///
        ///4.The adjustment will reduce receivables.
        ///
        ///5.Debit the allowance for bad debt account.
        ///
        ///6.Exit and update the batch.
        ///
        ///Additionally, you may want to update the customer in Accounts Receivable &gt; File &gt; Customers –Open.  If you want to continue to do business with this customer, you may just need to adjust the terms to refle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AR_WriteOffBadDebt_PDF {
            get {
                return ResourceManager.GetString("AR_WriteOffBadDebt_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Globey {
            get {
                object obj = ResourceManager.GetObject("Globey", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Globey2 {
            get {
                object obj = ResourceManager.GetObject("Globey2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
